### ISSUE TITLE
Gnosis safe transactions never complete

### ISSUE THREAD

**Issue by Namaskar-1F64F** [alwaysbegrowing/arbor-frontend#10]
Since the transactions go through the safe, you cannot use the tx hash returned first. That is the transaction to interact with the gnosis contract, I think you can use [transaction status](https://github.com/safe-global/safe-apps-sdk/tree/master/packages/safe-apps-sdk#retrieving-transactions-status) from the safe SDK to get the actual transaction.

**Comment by Bookcliff** [comment]
Fix addresses #25 also

**Comment by Bookcliff** [comment]
Fixed by https://github.com/alwaysbegrowing/arbor-frontend/pull/129
