### ISSUE TITLE
Issues claiming from a smart-contract wallet (Argent) 

### ISSUE THREAD

**Issue by RusseII** [alwaysbegrowing/arbor-frontend#106]
https://etherscan.io//tx/0x1ea3b9286829b0c5e3c49f2b6ac25e7a67211a204142462ecbc48f9d37c3faba 

* They can't claim their bonds via the UI 
* Their bid does now show up in the list of bids

They used Argent Wallet

**Comment by Bookcliff** [comment]
Closed by https://github.com/alwaysbegrowing/arbor-subgraph/pull/5
