### ISSUE TITLE
Convert window reactivity & investigation

### ISSUE THREAD

**Issue by Namaskar-1F64F** [alwaysbegrowing/arbor-frontend#113]
From [discord](https://discord.com/channels/992163551110250526/992823849324380170/1055383599030997062)

> Hi team, I appear to have lost 400 USDC because I converted the shapeshift bonds based on the price shown in the conversion window.

![Image](https://user-images.githubusercontent.com/7458951/209161195-353bfac2-d8d5-440c-8996-7b5c8afacccc.png)

**Comment by RusseII** [comment]
FYI we will be reimbursing the user for this

**Comment by Namaskar-1F64F** [comment]
closed by #115
