### ISSUE TITLE
Actions Through Gnosis Safe Never Confirm

### ISSUE THREAD

**Issue by Namaskar-1F64F** [alwaysbegrowing/arbor-frontend#25]
When creating a bond or auction, transactions are properly confirmed, but placing a bid and approving payment token in the auction page start the transaction, but never confirm. This leaves the UI in a perpetual loading state until refreshed. 

Here's a link for testing on the deployed testnet https://gnosis-safe.io/app/gor:0x09Cc51dECE5900B48A5851968C1FFc3F3C7676A6/apps?appUrl=https://goerli.arbor.garden

**Comment by Bookcliff** [comment]
Fixed by https://github.com/alwaysbegrowing/arbor-frontend/pull/129
