### ISSUE TITLE
Can't create bond 

### ISSUE THREAD

**Issue by RusseII** [alwaysbegrowing/arbor-frontend#6]
Maybe not on allow-list? Could debug by simulating transaction on tenderly. 
0xcafea1A2c9F4Af0Aaf1d5C4913cb8BA4bf0F9842
https://video.russell.work/WFewIE

**Comment by Geczy** [comment]
can you try on preview https://github.com/alwaysbegrowing/arbor-frontend/pull/7

**Comment by Namaskar-1F64F** [comment]
I think it was the token not on the allow list after deploying a new bond contract. I created this video from a new wallet to confirm: https://cln.sh/i8SpQm
