### ISSUE TITLE
Optimize Bond & Auction Flow for Scheduled Transactions

### ISSUE THREAD

**Issue by Namaskar-1F64F** [alwaysbegrowing/arbor-frontend#74]
The Bond and Auction are not user friendly to the idea of scheduled transactions. 

_need to confirm what we're actually building for. I believe most DAOs use gnosis safes, @RusseII?_

This can be seen in the Auction creation flow where the bond token allowance must be approved. If that transaction is scheduled, our app doesn't know and assumes the token is not approved. This prevents the auction from being made. 

Possible idea is a some toggle for "scheduled transactions" which would turn off the safeguards of token approval. this would assume that the token is approved and will allow auction creation.

Maybe we can detect the queued txs?  Via safe sdk or something.

What parts could be improved?

- [x] Bond needs to approve collateral token before bond creation
- [x] Promissory note & Auction needs to know the bond before auction creation
    - we can pre-calculate the bond address
- [x] Auction needs to approve bond token before auction creation

also see #25 and #10

**Comment by RusseII** [comment]
We should also allow users to override the approval block when trying to bid. Right now if bidding from a gnosis safe it's a very bad experience where you can't schedule both of the transactions, you have to execute the approve transaction before being able bid

**Comment by Bookcliff** [comment]
- [ ] Add arbor to safe apps (https://docs.gnosis-safe.io/build/sdks/safe-apps/releasing-your-safe-app) ?
