### ISSUE TITLE
shashguestions

### ISSUE THREAD

**Issue by Namaskar-1F64F** [alwaysbegrowing/arbor-frontend#87]
https://www.loom.com/share/5a8f2e111abc41a4b12b59a3fd762cb4

**Comment by Bookcliff** [comment]
- [ ] Prioritize the interest rate, collateralization ratio, current order volume (maybe make those green)
- [ ] Display credora, prime ratings more prominantly?

**Comment by Bookcliff** [comment]
Closed with https://github.com/alwaysbegrowing/arbor-frontend/pull/125 and https://github.com/alwaysbegrowing/arbor-frontend/pull/124
