### ISSUE TITLE
Enable Mobile

### ISSUE THREAD

**Issue by RusseII** [alwaysbegrowing/arbor-frontend#90]
Allow app to be viewed on mobile. We don't need to fully support everything, but it would be nice if we could make things work on mobile in portrait mode.

I don't expect people to make transactions on mobile, but they may use it to learn more / check the status of the auction

**Comment by Bookcliff** [comment]
- [ ] Offering table page
- [ ] Individual auctions page
- [ ] Bond table page
- [ ] Individual bonds page
- [ ] Portfolio
